### PR TITLE
docs: improve language style and more

### PR DESCRIPTION
**Pull request by salim-b**
Improve language, formatting and add more links.

### CODE REVIEW

**Review by razonyang — APPROVED** [review]

**Comment by razonyang** [comment]
Thank you!

**Comment by salim-b** [comment]
I am just discovering what an incredibly neatly constructed Hugo building block infrastructure you've built with hugomods.com and hbstack.dev. I am deeply impressed.

If I wanted to port the [doks-core]() theme from the Hyas project (which is based on Bootstrap 5) to Hugopress, would you recommend to base the theme on the [hbstack](https://github.com/hbstack) modules?

**Comment by razonyang** [comment]
> If I wanted to port the [doks-core](https://github.com/gethyas/doks-core) theme from the Hyas project (which is based on Bootstrap 5) to Hugopress

The work is a bit heavy, I'm not sure if HugoPress and HB modules are perfect for refactoring the theme, I'm still experimenting with them, and because of that, I didn't write some article on how to build a theme with HB. 

> would you recommend to base the theme on the [hbstack](https://github.com/hbstack) modules?

I didn't get it, since your theme is very popular, if you mean recommend your theme on the hbstack.dev site, then sure, I'm planning to modify the [themes](https://hbstack.dev/en/themes/) pages to include any themes base on HB, but there isn't any known third-party themes so far 😞.

**Comment by salim-b** [comment]
> I didn't get it

I meant if you think whether the hbstack modules are well suited or if they're too opinionated. I've only just began exploring all your work, so I'm not too familiar with internals yet... 😅

> I'm not sure if HugoPress and HB modules are perfect for refactoring the theme

I think they are, actually. You are very careful in separating and modularizing code, so I think it makes absolute sense to stand on your shouders 😉

I'm not doing stuff for popularity but for sustainability (incl. minimizing duplicate work). Popularity might follow naturally over time.

**Comment by razonyang** [comment]
I couldn't say that it suits the needs perfectly, there are some limitations of HB and HugoPress, hope it helps.

1. The SCSS and JS files import order is uncertain (perhaps by module name alphabetical), that is, it's impossible to make some module JS to be processed before others modules, not sure if it will be an issue, lack of use case.
1. `publishDir` must be `public`, HB relies on it to share PurgeCSS configs of modules.
1. Currently, HugoPress loads attributes and hooks by `weight` attribute (smaller gets high priority) and the module name alphabetical, which mean it maybe hard to control the sequence of modules, but it's also a rare use case.
1. There maybe some potential issues I don't know.

**Comment by salim-b** [comment]
Thank you so much for the insights!

Regarding

1. By "uncertain" you mean you don't actually know / care about the exact order the `assets` from your various modules with Hugopress' standardized/"automagic" assets inclusion are processed? Or is there actually some randomness involved?

   In any case, I think it's still superior to the npm-only approach from Hyas [which relies on Hugo modules `mount` ability beyond what it was originally designed for](https://discourse.gohugo.io/t/how-to-inspect-hugos-virtual-union-filesystem/46190/6). This leads to [totally annoying unpredictable and annoying overlay behaviour](https://discourse.gohugo.io/t/how-to-inspect-hugos-virtual-union-filesystem/46190/3).
   
   The underlying issue is that Hyas author pursues the primary/overall goal of [doing everything with npm and completely avoiding Hugo module *imports*](https://github.com/orgs/gethyas/discussions/420). At first I thought it would be mostly a matter of taste and wouldn't bother me too much since eventually we rely on npm anyways. But while [contributing quite a lot to doks-core](https://github.com/gethyas/doks-core/pulls?q=is%3Apr+author%3Asalim-b) I "climbed" a rather steep learning curve and came to the conclusion that what I really want is to embrace Hugo modules, i.e. properly set up Hugo module imports and stop managing Hugo dependencies via npm.
   
   Currently, Hyas/Doks replicates *a lot* of template code that is found in third-party Hugo modules like yours. And some of it is clearly subpar compared to yours (e.g. KaTeX functionality). I want to stop this silly approach where we would have to manually backport improvements and instead start directly relying on code shared with the broader Hugo community (like your modules are intended for). I can't do this in doks-core directly since it is not supposed to *import* Hugo modules. Hence my thoughts about porting the theme.
   
2. This is totally fine.

3. I have to look further into that but I guess since you have an explicit way to define the order via `weight`, this is cool.

4. I'd be happy to report them and contribute upstream when stumbling upon such issues.

I will probably experiment a bit in the coming weeks and report back. Thank you again!

**Comment by razonyang** [comment]
> 1. By "uncertain" you mean you don't actually know / care about the exact order the `assets` from your various modules with Hugopress' standardized/"automagic" assets inclusion are processed?

The module's SCSS and JS are imported in alphabetical (the module/folder name) order, but it's possible to improve it, but I have no ideal mechanism/algorithum to sort them.

> 1. came to the conclusion that what I really want is to embrace Hugo modules

Although I'm trying to manage dependencies without NPM, HB still need NPM to install some CLI tools and their dependencies, i.e. the PostCSS CLI, RTLCSS, Autoprefixer and PurgeCSS, http://localhost:13131/en/docs/getting-started/prerequisites/#nodejs. But HB doesn't mount the NPM packages (node_modules).

> I don't consider this to be a problem per se since the two differ quite largely in styling .

That's totally fine, everyone has their own taste, that's why I modularize the theme, so that everyone can create themes in different styles with the existing modules.

Some tips about getting start with HB for your theme.

1. If you're going to reuse the header and footer module, I'd suggest you use the [base](https://github.com/hbstack/base) module, otherwise create from scratch with `https://github.com/hbstack/hb`.
2. The [base](https://github.com/hbstack/base) and [blog](https://github.com/hbstack/blog) modules are good examples to help you understand how HB works.
3. If the theme requires other module, you'll need to import that module in configuration file.

**Comment by salim-b** [comment]
> Although I'm trying to manage dependencies without NPM, HB still need NPM to install some CLI tools and their dependencies (...) But HB doesn't mount the NPM packages (node_modules).

Sure, that's totally fine. Not mounting them is key.


Thank you for your further tips! 🙏

**Pull request merged**
